import type { NextPage } from 'next';
import Head from 'next/head';
import { PartnersGraph } from '../components/partners-graph';
import * as data from '../utils/data.json';

const Home: NextPage = () => {
  return (
    <div className="container mx-auto">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="md:container md:mx-auto">
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <PartnersGraph data={data} width={500} height={500} margin={{ top: 0, bottom: 0, left: 0, right: 0 }} />
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
