import type { NextPage } from 'next';
import Head from 'next/head';

import 'bootstrap/dist/css/bootstrap.css';
import 'line-awesome/dist/line-awesome/css/line-awesome.min.css';
import { NavBar } from '../components/navbar';
import { HomeParticles } from 'components/home-particles';
import Image from 'next/image';
import Logo from '@images/logo.png';
import Link from 'next/link';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>TUM.ai - For Partners</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />

      <header
        className="d-flex align-items-center"
        style={{ height: '50vh', background: '-webkit-linear-gradient(180deg, #151e35 0%, #211b44 100%)', zIndex: 3 }}
      >
        <div className="container">
          <div className="row justify-content-center">
            <div className="col-auto align-self-center">
              <HomeParticles />
              <div className="home-logo">
                <Image src={Logo.src} layout="fill" />
              </div>
            </div>
            <div className="col-12 text-center mt-3">
              <Link href="https://join-us.tum-ai.com" passHref={true}>
                <a className="btn btn-primary">Learn more about TUM.ai</a>
              </Link>
            </div>
          </div>
        </div>
      </header>

      <section className="container bg-white text-center">
        <div className="col p-5">
          <h1 className="display-2 fw-bold">WELCOME to TUM.ai</h1>
        </div>
      </section>
    </div>
  );
};

export default Home;
